project_id = "fgbenetdksqnvwkgnips"

[functions.create-instance]
verify_jwt = false

[functions.connect-instance]
verify_jwt = false

[functions.check-connection-status]
verify_jwt = false

[functions.delete-instance]
verify_jwt = false

[functions.start-campaign]
verify_jwt = false

[functions.send-campaign-messages]
verify_jwt = false

[functions.process-scheduled-campaigns]
verify_jwt = false

[functions.generate-template-variations]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.list-invoices]
verify_jwt = true

[functions.admin-update-subscription]
verify_jwt = true
